#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
set -euo pipefail

# shellcheck disable=SC2154
docker build \
  --build-arg BUILD_VERSION="${DOCKER_TAG}" \
  --pull \
  --file "${DOCKERFILE_PATH}" \
  --tag "${IMAGE_NAME}" .
