#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
set -euo pipefail

# shellcheck disable=SC2154
if [[ "${DOCKER_TAG}" =~ ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$ ]]; then
    IFS='.' read -r -a version_array <<<"${DOCKER_TAG}"
    readonly MAJOR="${version_array[0]}"
    readonly MINOR="${version_array[1]}"
    readonly LATEST_MINOR="${MAJOR}.${MINOR}"

    docker tag "${IMAGE_NAME}" "${DOCKER_REPO}:${LATEST_MINOR}"
    if [[ "$*" != "--dry-run" ]]; then
        docker push "${DOCKER_REPO}:${LATEST_MINOR}"
    fi
fi

docker tag "${IMAGE_NAME}" "${DOCKER_REPO}:latest"
if [[ "$*" != "--dry-run" ]]; then
    docker push "${DOCKER_REPO}:latest"
fi
